name: Tilray-Infra-test
on:
  workflow_dispatch:

env:
  AZURE_SUBSCRIPTION: bcdf2f15-1f15-49b0-8ba7-c4fb87a2fc20
  AZURE_RESOURCE_GROUP: rg-tilray-it-test-cace
  TEMPLATE_FILE_PATH: ./Infra/main.bicep
  PARAMETERS_FILE_PATH: ./Infra/test.params.json

jobs:
  what-if:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

      # Log into Azure
    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_TEST }}

      # What-If step
    - name: Run What-If
      run: |
        az bicep install
        az deployment group what-if --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --template-file ${{ env.TEMPLATE_FILE_PATH }} --parameters ${{ env.PARAMETERS_FILE_PATH }}

  approval:
    needs: what-if
    runs-on: ubuntu-latest
    environment:
      name: test
    steps:
      - name: Approval Required
        run: echo "Waiting for approval to proceed with deployment..."

  deploy:
    needs: approval
    runs-on: ubuntu-latest
    steps:
      # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

      # Log into Azure
    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_TEST }}

      # Deploy Bicep file
    - name: Deploy
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
        template: ${{ env.TEMPLATE_FILE_PATH }}
        parameters: ${{ env.PARAMETERS_FILE_PATH }}
        failOnStdErr: false
        deploymentMode: 'Incremental'
