name: Deploy .NET to Azure Functions

on:
  push:
    branches: ["test"]

env:
  AZURE_FUNCTIONAPP_NAME: 'func-tilray-it-ais-test-cace-01'  
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/Adapters/Web/FunctionApp'        
  DOTNET_VERSION: '8.0.x'                    # .NET version 
  AZURE_RESOURCE_GROUP: 'rg-tilray-it-test-cace' # Replace with your Azure resource group name
  ENVIRONMENT: dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Use 'windows-latest' for Windows
    environment: ${{ env.ENVIRONMENT }} # Use environment-specific secrets
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} # Azure RBAC credentials

    - name: 'Set up .NET'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Restore Dependencies'
      run: dotnet restore ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

    - name: 'Build Project'
      run: dotnet build ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} --configuration Release --output ./output

    - name: 'Run Unit Tests'
      run: dotnet test ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} --configuration Release --no-build

    - name: 'Publish Project'
      run: dotnet publish ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} --configuration Release --output ./output

    - name: 'Deploy to Azure Functions'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        slot-name: 'production' # Optional: Deploy to a specific slot

    - name: 'Logout from Azure'
      run: az logout